server:
  port: 9999
  address: 0.0.0.0
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    username: root
    password: BlackWater
    url: jdbc:mysql://127.0.0.1:3307/video_hosting_db

logging:
  level:
    org.springframework.web: DEBUG
