version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: hosting_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - "mysql_volume:/var/lib/mysql"
    networks:
      - spring_boot_network

  spring:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_app
    env_file:
      - .env
    depends_on:
      - mysql
      - elastic_search
    volumes:
      - "${HOSTING_APP_LOCATION}/spring_conf:/app/spring_conf"
      - "spring_storage:/app/spring_storage"
    ports:
      - "${HOSTING_PORT}:${HOSTING_PORT}"
    environment:
      SPRING_CONFIG_LOCATION: "file:/app/spring_conf/application.yml"
    networks:
      - spring_boot_network

  elastic_search:
    container_name: elastic_search
    image: elasticsearch:8.16.2
    ports:
      - "${ELASTIC_PORT}:${ELASTIC_PORT}"
    volumes:
      - "elastic_volume:/usr/share/elasticsearch/data"
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
    networks:
      - spring_boot_network

volumes:
  mysql_volume:
  spring_storage:
  elastic_volume:

networks:
  spring_boot_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.255.0/24"
          gateway: "172.16.255.1"
