services:
  video_hosting_app:
    hostname: video-hosting-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      video_hosting_db:
        condition: service_healthy
      video_hosting_search:
        condition: service_healthy
    volumes:
      - "${VIDEO_HOSTING_APP_LOCATION}/spring_conf:${VIDEO_HOSTING_CONFIG_PATH}"
      - "video_hosting_app_volume:${VIDEO_HOSTING_STORAGE_PATH}"
    ports:
      - "${VIDEO_HOSTING_HTTP_PORT}:${VIDEO_HOSTING_HTTP_PORT}"
    environment:
      SPRING_CONFIG_LOCATION: "file:${VIDEO_HOSTING_CONFIG_PATH}/application.yml"
    networks:
      - video_hosting_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
  video_hosting_db:
    hostname: video-hosting-db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - "video_hosting_db_volume:/var/lib/mysql"
    networks:
      - video_hosting_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_PASSWORD}"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 15s
  video_hosting_search:
    hostname: video-hosting-search
    image: elasticsearch:9.3.1
    ports:
      - "${ELASTIC_PORT}:${ELASTIC_PORT}"
    volumes:
      - "video_hosting_search_volume:/usr/share/elasticsearch/data"
    environment:
      - "discovery.type=single-node"
      - "ELASTIC_USERNAME=${ELASTIC_USERNAME}"
      - "ELASTIC_PASSWORD=${ELASTIC_PASSWORD}"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - video_hosting_network
    healthcheck:
      test: ["CMD-SHELL", "curl -u ${ELASTIC_USERNAME}:${ELASTIC_PASSWORD} http://localhost:${ELASTIC_PORT}/_cluster/health || exit 1"]
      interval: 20s
      timeout: 15s
      retries: 5
      start_period: 3m

volumes:
  video_hosting_db_volume:
  video_hosting_app_volume:
  video_hosting_search_volume:

networks:
  video_hosting_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.1.0/28"
          gateway: "172.16.1.1"
