server:
  port: 9999
  address: 0.0.0.0

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    username: mikhail_shell
    password: BlackWater
    url: jdbc:mysql://127.0.0.1:3306/video_hosting_db

logging:
  level:
    org.springframework.web: DEBUG

hosting:
  server:
    ip: 192.168.1.101 #158.160.22.54
  storage:
    path: "C:/VideoHostingStorage"
