server:
  port: 9999

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    username: mikhail_shell
    password: BlackWater
    url: jdbc:mysql://127.0.0.1:3306/video_hosting_db

logging:
  level:
    org.springframework.web: DEBUG