server:
  port: ${HOSTING_PORT:8080}
  address: 0.0.0.0

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    url: jdbc:mysql://hosting_db:3306/${MYSQL_DATABASE}
  jpa:
    show-sql: true
  elasticsearch:
    rest:
      uris: [ http://elastic_search:9200 ]

logging:
  level:
    org.springframework.web: DEBUG
    org:
      elasticsearch: DEBUG
      elasticsearch.client: DEBUG
    springframework:
      data.elasticsearch: DEBUG

hosting:
  server:
    ip: ${HOSTING_IP}
  storage:
    path: "/app/spring_storage"
