server:
  port: ${HOSTING_PORT:8080}
  address: 0.0.0.0

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    url: jdbc:mysql://hosting_db:3306/${MYSQL_DATABASE}

logging:
  level:
    org.springframework.web: DEBUG

hosting:
  server:
    ip: ${HOSTING_IP}
  storage:
    path: "/app/spring_storage"

