server:
  port: ${HOSTING_HTTPS_PORT}
  address: 0.0.0.0
  http:
    port: ${HOSTING_HTTP_PORT}
  ssl:
    key-store: ${KEYSTORE_PATH}
    key-store-password: ${KEYSTORE_PASSWORD}
    keyStoreType: ${KEYSTORE_TYPE}
    keyAlias: ${KEY_ALIAS}

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
    url: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
  jpa:
    show-sql: true

  elasticsearch:
    uris: http://elastic:${ELASTIC_PORT}
    username: ${ELASTIC_USERNAME}
    password: ${ELASTIC_PASSWORD}
    connection-timeout: 5s
    socket-timeout: 10s
    sniff: false

logging:
  level:
    org.springframework.web: DEBUG
    org:
      elasticsearch: DEBUG
      elasticsearch.client: DEBUG
    springframework:
      data.elasticsearch: DEBUG

hosting:
  server:
    host: ${HOST}
  application:
    path: "/app"
  storage:
    path: "/app/spring_storage"
