server:
  port: ${HOSTING_HTTP_PORT}
  address: 0.0.0.0

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    url: jdbc:mysql://video_hosting_db:${MYSQL_PORT}/${MYSQL_DATABASE}
  jpa:
    show-sql: true
  elasticsearch:
    uris: http://host.docker.internal:${ELASTIC_PORT}
    username: ${ELASTIC_USERNAME}
    password: ${ELASTIC_PASSWORD}
    connection-timeout: 5s
    socket-timeout: 10s
    sniff: false
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.springframework.web: DEBUG
    org:
      elasticsearch: DEBUG
      elasticsearch.client: DEBUG
    springframework:
      data.elasticsearch: DEBUG

hosting:
  server:
    host: ${HOST}
  application:
    path: ${HOSTING_APP_PATH}
    ranking:
      weights:
        date-time: 0.00000005
        subscribers: 0.01
        views: 0.01
        likes: 0.005
        dislikes: -0.005
  android:
    domain:
      verification:
        url: ${ANDROID_DOMAIN_VERIFICATION}
  storage:
    path: ${HOSTING_STORAGE_PATH}